export enum TelegramScene {
  REGISTRATION = 'REGISTRATION',
  REGISTRATION_HANDLER = 'REGISTRATION_HANDLER',
  GAME_GREET = 'GAME_GREET',
  GAME_GREET_HANDLER = 'GAME_GREET_HANDLER',
  GAME = 'GAME',
  GAME_HANDLER = 'GAME_HANDLER',
  EXIT = 'EXIT'
}
